# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT"
[[mods]] #mandatory
# The modid of the mod
modId="jeiutilities" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="JEI Utilities" #mandatory
# A text field displayed in the mod UI
credits="Thanks for the idea from NEI easy search" #optional
# A text field displayed in the mod UI
authors="vfyjxf_" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
TMore enhancements for JEI
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.jeiutilities]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.jeiutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeiutilities]]
modId="jei"
mandatory=true
versionRange="[9.7.0.209,)"
ordering="AFTER"
side="CLIENT"
